# Generated by Django 4.2.3 on 2023-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('emp_code', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('numberphone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeoCode',
            fields=[
                ('location_code', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('created_date', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'geo_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('school_code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('location_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('created_date', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'school_detail',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='geo_code',
        ),
        migrations.DeleteModel(
            name='school_detail',
        ),
    ]
