# Generated by Django 4.2.3 on 2023-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0002_employeedetail_geocode_schooldetail_delete_geo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('majors_code', models.AutoField(primary_key=True, serialize=False)),
                ('majors_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'majors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolMajors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
