# Generated by Django 4.2.3 on 2023-08-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0003_majors_schoolmajors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schoolmajors',
            table='school_majors',
        ),
    ]
